### ISSUE TITLE
Off-by-one error in `key_from_point`

### ISSUE THREAD

**Issue by Easyoakland** [johanhelsing/bevy_sparse_grid_2d#5]
Just a heads up I'm pretty sure you have an off-by-one error [here](https://github.com/johanhelsing/bevy_sparse_grid_2d/blob/4541c84231d8b0fd1b6bdb6fe3d70e188f373a74/src/lib.rs#L82C1-L87)

Since the first positive key space tile index is `0` but the first negative key space tile is index `-1`
I think this should be
```rust
         (point.x / TILE_SIZE as f32).floor() as i32,
         (point.y / TILE_SIZE as f32).floor() as i32,
```

**Comment by johanhelsing** [comment]
Ah, you're right. Since it's happening both when storing and querying, the consequence is that the iterators for (0.5, 0.5), (-0.5, 0.5), (-0.5, -0.5) and (0.5, -0.5) will overlap (with `TILE_SIZE=1` for simple example). But otherwise it should be correct.

I didn't notice, since it's I use it only for collision broadphase, and they'll get discarded in the narrowphase.

Do you want to submit a PR? And a test perhaps?

**Comment by johanhelsing** [comment]
> Do you want to submit a PR? And a test perhaps?

Nvm, I had the project open, so figured I'd just do it. Thanks for the clear bug report!
